"""
SMALL AX AGENT — Prompt Library
모든 에이전트 프롬프트 중앙 관리
"""

from .interview_agent import (
    INTERVIEW_SYSTEM_PROMPT,
    INTERVIEW_FEW_SHOTS,
    INTERVIEW_TURN_TEMPLATE,
    SOPHISTICATION_DETECTOR_PROMPT,
    HISTORY_COMPRESSION_PROMPT,
    build_interview_prompt,
)

from .workflow_decomposer import (
    DECOMPOSER_SYSTEM_PROMPT,
    DECOMPOSER_FEW_SHOTS,
    DECOMPOSER_USER_TEMPLATE,
    DECOMPOSITION_VERIFIER_PROMPT,
)

from .ax_review_architect_toolmapper import (
    AX_REVIEW_SYSTEM_PROMPT,
    AX_REVIEW_FEW_SHOTS,
    ARCHITECT_SYSTEM_PROMPT,
    ARCHITECT_REFINEMENT_PROMPT,
    TOOL_MAPPER_SYSTEM_PROMPT,
    TOOL_MAPPER_CONTEXT_TEMPLATE,
)

from .code_generator import (
    CODE_GENERATOR_SYSTEM_PROMPT,
    CODE_FEW_SHOT_SMARTSTORE,
    LLM_COMPONENT_PROMPT,
    CODE_SELF_CRITIQUE_PROMPT,
    TEST_GENERATION_PROMPT,
)

from .verifier_meta_chaining import (
    VERIFIER_SYSTEM_PROMPT,
    VERIFIER_CONTEXT_TEMPLATE,
    META_PROMPT_GENERATOR,
    META_PROMPT_DOMAINS,
    CHAIN_HANDOFF_SCHEMA,
    CHAIN_CONTEXT_COMPRESSOR,
    CHAIN_ORCHESTRATOR_PROMPT,
    CONSTITUTIONAL_RULES,
    PIPELINE_REFLECTION_PROMPT,
    assemble_agent_prompt,
)

__all__ = [
    # Interview
    "INTERVIEW_SYSTEM_PROMPT", "INTERVIEW_FEW_SHOTS", "INTERVIEW_TURN_TEMPLATE",
    "SOPHISTICATION_DETECTOR_PROMPT", "HISTORY_COMPRESSION_PROMPT", "build_interview_prompt",
    # Decomposer
    "DECOMPOSER_SYSTEM_PROMPT", "DECOMPOSER_FEW_SHOTS", "DECOMPOSER_USER_TEMPLATE",
    "DECOMPOSITION_VERIFIER_PROMPT",
    # AX Review / Architect / Tool Mapper
    "AX_REVIEW_SYSTEM_PROMPT", "AX_REVIEW_FEW_SHOTS",
    "ARCHITECT_SYSTEM_PROMPT", "ARCHITECT_REFINEMENT_PROMPT",
    "TOOL_MAPPER_SYSTEM_PROMPT", "TOOL_MAPPER_CONTEXT_TEMPLATE",
    # Code Generator
    "CODE_GENERATOR_SYSTEM_PROMPT", "CODE_FEW_SHOT_SMARTSTORE",
    "LLM_COMPONENT_PROMPT", "CODE_SELF_CRITIQUE_PROMPT", "TEST_GENERATION_PROMPT",
    # Verifier + Meta + Chaining
    "VERIFIER_SYSTEM_PROMPT", "VERIFIER_CONTEXT_TEMPLATE",
    "META_PROMPT_GENERATOR", "META_PROMPT_DOMAINS",
    "CHAIN_HANDOFF_SCHEMA", "CHAIN_CONTEXT_COMPRESSOR", "CHAIN_ORCHESTRATOR_PROMPT",
    "CONSTITUTIONAL_RULES", "PIPELINE_REFLECTION_PROMPT", "assemble_agent_prompt",
]
